name: Auto Commit Streak

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          echo "Auto commit to maintain streak [$(date)]" >> streak.txt
          git add streak.txt
          git commit -m "Auto commit to maintain streak [$(date)]"

      - name: Push changes
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master
